//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerIncidents.IncidentsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Incident", Namespace="http://schemas.datacontract.org/2004/07/IncidentsService")]
    [System.SerializableAttribute()]
    public partial class Incident : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateClosedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOpenedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IncidentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TechIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateClosed {
            get {
                return this.DateClosedField;
            }
            set {
                if ((this.DateClosedField.Equals(value) != true)) {
                    this.DateClosedField = value;
                    this.RaisePropertyChanged("DateClosed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOpened {
            get {
                return this.DateOpenedField;
            }
            set {
                if ((this.DateOpenedField.Equals(value) != true)) {
                    this.DateOpenedField = value;
                    this.RaisePropertyChanged("DateOpened");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IncidentID {
            get {
                return this.IncidentIDField;
            }
            set {
                if ((this.IncidentIDField.Equals(value) != true)) {
                    this.IncidentIDField = value;
                    this.RaisePropertyChanged("IncidentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TechID {
            get {
                return this.TechIDField;
            }
            set {
                if ((this.TechIDField.Equals(value) != true)) {
                    this.TechIDField = value;
                    this.RaisePropertyChanged("TechID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IncidentsServiceReference.IIncidentService")]
    public interface IIncidentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetOpenTechIncidents", ReplyAction="http://tempuri.org/IIncidentService/GetOpenTechIncidentsResponse")]
        CustomerIncidents.IncidentsServiceReference.Incident[] GetOpenTechIncidents(int techID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetOpenTechIncidents", ReplyAction="http://tempuri.org/IIncidentService/GetOpenTechIncidentsResponse")]
        System.Threading.Tasks.Task<CustomerIncidents.IncidentsServiceReference.Incident[]> GetOpenTechIncidentsAsync(int techID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetCustomerIncidentsByID", ReplyAction="http://tempuri.org/IIncidentService/GetCustomerIncidentsByIDResponse")]
        CustomerIncidents.IncidentsServiceReference.Incident[] GetCustomerIncidentsByID(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetCustomerIncidentsByID", ReplyAction="http://tempuri.org/IIncidentService/GetCustomerIncidentsByIDResponse")]
        System.Threading.Tasks.Task<CustomerIncidents.IncidentsServiceReference.Incident[]> GetCustomerIncidentsByIDAsync(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetAllCustomerIncidents", ReplyAction="http://tempuri.org/IIncidentService/GetAllCustomerIncidentsResponse")]
        CustomerIncidents.IncidentsServiceReference.Incident[] GetAllCustomerIncidents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetAllCustomerIncidents", ReplyAction="http://tempuri.org/IIncidentService/GetAllCustomerIncidentsResponse")]
        System.Threading.Tasks.Task<CustomerIncidents.IncidentsServiceReference.Incident[]> GetAllCustomerIncidentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIncidentServiceChannel : CustomerIncidents.IncidentsServiceReference.IIncidentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IncidentServiceClient : System.ServiceModel.ClientBase<CustomerIncidents.IncidentsServiceReference.IIncidentService>, CustomerIncidents.IncidentsServiceReference.IIncidentService {
        
        public IncidentServiceClient() {
        }
        
        public IncidentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IncidentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncidentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncidentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CustomerIncidents.IncidentsServiceReference.Incident[] GetOpenTechIncidents(int techID) {
            return base.Channel.GetOpenTechIncidents(techID);
        }
        
        public System.Threading.Tasks.Task<CustomerIncidents.IncidentsServiceReference.Incident[]> GetOpenTechIncidentsAsync(int techID) {
            return base.Channel.GetOpenTechIncidentsAsync(techID);
        }
        
        public CustomerIncidents.IncidentsServiceReference.Incident[] GetCustomerIncidentsByID(int customerID) {
            return base.Channel.GetCustomerIncidentsByID(customerID);
        }
        
        public System.Threading.Tasks.Task<CustomerIncidents.IncidentsServiceReference.Incident[]> GetCustomerIncidentsByIDAsync(int customerID) {
            return base.Channel.GetCustomerIncidentsByIDAsync(customerID);
        }
        
        public CustomerIncidents.IncidentsServiceReference.Incident[] GetAllCustomerIncidents() {
            return base.Channel.GetAllCustomerIncidents();
        }
        
        public System.Threading.Tasks.Task<CustomerIncidents.IncidentsServiceReference.Incident[]> GetAllCustomerIncidentsAsync() {
            return base.Channel.GetAllCustomerIncidentsAsync();
        }
    }
}
